[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "22"

[dev]
  framework = "#custom"
  command = "sh .netlify-dev-noop.sh"
  targetPort = 4399
  port = 4323
  autoLaunch = false
